# PRODUCTION DATABASE

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY

spring.flyway.enabled=true
spring.flyway.clean-disabled=true


# LOGGING

logging.level.com.snehal.linkpulse=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN