spring.application.name=linkpulse-backend

# JPA / HIBERNATE CONFIG

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY CONFIG

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# active profile
spring.profiles.active=dev